from typing import List

from app.schemas.complaint import ComplaintDraft, ComplaintRequest


def generate_complaint(req: ComplaintRequest) -> ComplaintDraft:
    cat = req.category or "GENERAL"
    subject = f"Request for assistance regarding {cat.replace('_', ' ').title()}"
    summary = (req.user_statement or "").strip()[:400] or "User described an incident and requested a draft record."
    when = " ".join(x for x in [req.date, req.time] if x) or "Date/time to be filled by the user"
    where = req.location_text or "Location to be filled by the user"
    evidence = req.evidence_names or ["(none listed yet — add after review)"]
    recipient = {
        "TRAFFIC_STOP": "Appropriate traffic / police documentation channel (user must confirm)",
        "BRIBE_DEMAND": "Legitimate anti-corruption or vigilance complaint channel (user must confirm)",
        "SCAM": "Cybercrime / bank fraud reporting channel (user must confirm)",
        "THREAT_HARASSMENT": "Local police / legal-aid (user must confirm)",
        "LEGAL_NOTICE": "Qualified legal professional / legal-aid (user must confirm)",
    }.get(cat, "Legitimate authority the user selects after review")

    body = f"""DRAFT FOR REVIEW — DO NOT SUBMIT AUTOMATICALLY
This draft was generated by NyaySetu AI for the user to edit. It is not a filing.

Subject: {subject}

Incident summary:
{summary}

When: {when}
Where: {where}

Detailed description:
{req.user_statement}

Evidence listed by user:
{chr(10).join('- ' + e for e in evidence)}

Requested action:
Please take appropriate action through official procedure. I request acknowledgment of this complaint and guidance on next steps.

Recipient category (suggested, not verified): {recipient}

Context notes:
{(req.retrieved_context or 'None').strip()[:800]}

I declare that I will review and correct this draft before sharing it with any authority.
"""
    return ComplaintDraft(
        subject=subject,
        incident_summary=summary,
        detailed_description=req.user_statement,
        evidence_list=evidence,
        requested_action="Review this draft, correct facts, then share only through a channel you have verified.",
        recipient_category=recipient,
        body=body,
        demo_mode=False,
    )
